CREATE TABLE "section_representative_claim" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "section_representative_claim_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"section_id" integer NOT NULL,
	"position" "representative_position" NOT NULL,
	"student_code" varchar(30) NOT NULL,
	"full_name" varchar(150) NOT NULL,
	"observed_at" timestamp with time zone NOT NULL,
	CONSTRAINT "uq_section_representative_claim_position" UNIQUE("section_id","position")
);
--> statement-breakpoint
ALTER TABLE "section_representative_claim" ADD CONSTRAINT "section_representative_claim_section_id_section_id_fk" FOREIGN KEY ("section_id") REFERENCES "public"."section"("id") ON DELETE no action ON UPDATE no action;