CREATE TABLE "course_equivalence" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "course_equivalence_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"curriculum_id" integer NOT NULL,
	"legacy_code" varchar(30) NOT NULL,
	"curriculum_course_id" integer NOT NULL,
	"source" varchar(120) NOT NULL,
	CONSTRAINT "uq_course_equivalence" UNIQUE("curriculum_id","legacy_code")
);
--> statement-breakpoint
ALTER TABLE "course_equivalence" ADD CONSTRAINT "course_equivalence_curriculum_id_curriculum_id_fk" FOREIGN KEY ("curriculum_id") REFERENCES "public"."curriculum"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "course_equivalence" ADD CONSTRAINT "course_equivalence_curriculum_course_fk" FOREIGN KEY ("curriculum_course_id","curriculum_id") REFERENCES "public"."curriculum_course"("id","curriculum_id") ON DELETE no action ON UPDATE no action;