-- RS-BE-22, RS-BE-24 y RS-BE-25 · Copia del récord académico del portal.
--
-- Tres tablas nuevas y ninguna columna tocada de las que ya existen:
--   student_record_entry       una fila por curso del récord (ciclo, código, vez).
--   student_academic_snapshot  una fila por alumno: PPA, ubicación relativa y créditos.
--   student_period_summary     una fila por ciclo del bloque "por período" de layout.jsp.
--
-- Son una copia del portal, no datos propios de la app: cada sincronización
-- aceptada las reemplaza enteras, y el alumno puede borrarlas cuando quiera
-- (DELETE /academic-record/me). Las tres cuelgan de "student" con borrado en
-- cascada: si algún día se borra a un alumno, su récord no queda huérfano.
--
-- Sin relación con la malla, a propósito (RS-BE-22): el récord es histórico y
-- trae cursos de planes anteriores que ya no existen en la malla vigente. Se
-- guardan con el código y el nombre que publica el portal.
--
-- Los nombres y las observaciones son "text" y no "varchar(n)": un valor más
-- largo que el límite abortaría TODA la transacción de la importación, y con
-- ella el horario y la matrícula del alumno. Por lo mismo, ni el PPA ni el
-- promedio del ciclo llevan CHECK de rango. Los tres CHECK que sí van —vez >= 1,
-- créditos >= 0 y nota entre 0 y 20— ya los garantiza el parser (RS-BE-19), así
-- que no pueden dispararse por un dato inesperado del portal.
--
-- Aditiva e idempotente: las tres tablas y el índice llevan IF NOT EXISTS y los
-- CONSTRAINT viajan dentro de la definición, así que se puede re-aplicar sin daño.
--
--   bun run db:apply drizzle/0011_academic_record.sql
--
-- Con db:apply y NO con db:migrate ni db:generate: drizzle/meta/_journal.json
-- se quedó en la 0009 (9 entradas), así que ni la 0010 ni esta quedan
-- registradas ahí.

CREATE TABLE IF NOT EXISTS "student_record_entry" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "student_record_entry_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"student_id" integer NOT NULL,
	"period_code" varchar(10) NOT NULL,
	"course_code" varchar(10) NOT NULL,
	"course_name" text NOT NULL,
	"attempt" smallint NOT NULL,
	"credits" numeric(4, 1) NOT NULL,
	"grade" smallint,
	"grade_raw" text,
	"section_code" text,
	"observation" text,
	CONSTRAINT "uq_student_record_entry" UNIQUE("student_id","period_code","course_code","attempt"),
	CONSTRAINT "chk_student_record_entry_attempt" CHECK ("student_record_entry"."attempt" >= 1),
	CONSTRAINT "chk_student_record_entry_credits" CHECK ("student_record_entry"."credits" >= 0),
	CONSTRAINT "chk_student_record_entry_grade" CHECK ("student_record_entry"."grade" IS NULL OR "student_record_entry"."grade" BETWEEN 0 AND 20),
	CONSTRAINT "student_record_entry_student_id_student_id_fk" FOREIGN KEY ("student_id") REFERENCES "public"."student"("id") ON DELETE cascade ON UPDATE no action
);
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "idx_student_record_entry_student" ON "student_record_entry" USING btree ("student_id");
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "student_academic_snapshot" (
	"student_id" integer PRIMARY KEY NOT NULL,
	"ppa" numeric(6, 4),
	"relative_position" text,
	"convalidated_courses" integer,
	"convalidated_credits" numeric(6, 1),
	"approved_courses" integer,
	"approved_credits" numeric(6, 1),
	"credits_accumulated" numeric(6, 1),
	"credits_required" numeric(6, 1),
	"synced_at" timestamp with time zone NOT NULL,
	CONSTRAINT "student_academic_snapshot_student_id_student_id_fk" FOREIGN KEY ("student_id") REFERENCES "public"."student"("id") ON DELETE cascade ON UPDATE no action
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "student_period_summary" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "student_period_summary_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"student_id" integer NOT NULL,
	"period_code" varchar(10) NOT NULL,
	"average" numeric(6, 4),
	"relative_position" text,
	"level" smallint,
	"convalidated_courses" integer,
	"convalidated_credits" numeric(6, 1),
	"enrolled_courses" integer,
	"enrolled_credits" numeric(6, 1),
	"approved_courses" integer,
	"approved_credits" numeric(6, 1),
	"failed_courses" integer,
	"failed_credits" numeric(6, 1),
	CONSTRAINT "uq_student_period_summary" UNIQUE("student_id","period_code"),
	CONSTRAINT "student_period_summary_student_id_student_id_fk" FOREIGN KEY ("student_id") REFERENCES "public"."student"("id") ON DELETE cascade ON UPDATE no action
);
