-- RS-BE-30 · Bloques de horario propios del alumno (prácticas, trabajo, voluntariado).
--
-- Un tipo enumerado y dos tablas nuevas; ninguna columna tocada de las que ya existen:
--   time_block_exception_status   estado de un día que se sale del patrón.
--   student_time_block            la REGLA: título, color, días, horas y rango de fechas.
--   student_time_block_exception  una fila por fecha que se sale de esa regla.
--
-- Por qué tabla aparte y no `schedule_session`: esa tabla tiene `section_id`
-- NOT NULL apuntando a `section`, su unique es (section_id, day_of_week,
-- start_time) y `recomputeOfferingHoursFromSchedule` (portal-sync.repository.ts:599)
-- suma TODAS sus filas de una sección para pisar `course_offering.total_hours`,
-- que es el denominador del % de inasistencia. Un bloque personal ahí dentro
-- falsearía el riesgo de impedimento de todos los matriculados en esa sección.
--
-- Sin relación con curso, sección, ciclo ni matrícula (decisión 5 de la spec):
-- unas prácticas preprofesionales cruzan ciclos y vacaciones, así que la
-- vigencia son fechas propias del bloque. Es la primera tabla del horario con
-- fechas de inicio y fin suyas.
--
-- Las dos cuelgan con borrado en cascada: la excepción muere con su bloque y el
-- bloque muere con su alumno.
--
-- Por qué CHECK y no solo Zod: a diferencia del récord, este dato no viene de
-- un portal que no controlamos sino de un formulario que sí controlamos, y un
-- valor imposible —hora de fin antes de la de inicio, color inventado— haría
-- que la grilla pinte basura o no pinte nada. Un rechazo es un error del
-- alumno, no una importación entera perdida.
--
-- `chk_time_block_dias` envuelve `array_length` en `coalesce(…, 0)` a
-- propósito: sobre un arreglo vacío `array_length` devuelve NULL, y una
-- restricción que evalúa a NULL se da por satisfecha, así que sin el coalesce
-- un `days_of_week` vacío entraría igual. La spec pide "entre 1 y 7 valores";
-- esto es lo que hace que eso se cumpla también en la base.
--
-- Aditiva e idempotente: el tipo enumerado se crea dentro de un bloque DO
-- guardado contra `duplicate_object`, las dos tablas y el índice llevan
-- `IF NOT EXISTS` y las restricciones viajan dentro de la definición, así que
-- se puede re-aplicar sin daño. Crear un tipo nuevo sí es transaccional: la
-- trampa de MIGRATIONS.md:125 es agregarle un valor a un tipo que YA existe,
-- que no es transaccional y revienta dentro de db:apply; acá no se hace.
--
--   bun run db:apply drizzle/0012_time_blocks.sql
--
-- Con db:apply y NO con db:migrate ni db:generate: drizzle/meta/_journal.json
-- se quedó en la 0009 (9 entradas), así que ni la 0010, ni la 0011, ni esta
-- quedan registradas ahí.

DO $$ BEGIN
  CREATE TYPE "public"."time_block_exception_status" AS ENUM('cancelled', 'moved');
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "student_time_block" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "student_time_block_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"student_id" integer NOT NULL,
	"title" varchar(60) NOT NULL,
	"color_hex" varchar(7) NOT NULL,
	"days_of_week" smallint[] NOT NULL,
	"start_time" time NOT NULL,
	"end_time" time NOT NULL,
	"start_date" date NOT NULL,
	"end_date" date NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "chk_time_block_horas" CHECK ("student_time_block"."end_time" > "student_time_block"."start_time"),
	CONSTRAINT "chk_time_block_grilla" CHECK ("student_time_block"."start_time" >= '07:00' AND "student_time_block"."end_time" <= '22:00'),
	CONSTRAINT "chk_time_block_fechas" CHECK ("student_time_block"."end_date" >= "student_time_block"."start_date"),
	CONSTRAINT "chk_time_block_dias" CHECK (coalesce(array_length("student_time_block"."days_of_week", 1), 0) BETWEEN 1 AND 7 AND "student_time_block"."days_of_week" <@ ARRAY[1,2,3,4,5,6,7]::smallint[]),
	CONSTRAINT "chk_time_block_color" CHECK ("student_time_block"."color_hex" ~ '^#[0-9A-Fa-f]{6}$'),
	CONSTRAINT "chk_time_block_titulo" CHECK (length(btrim("student_time_block"."title")) BETWEEN 1 AND 60),
	CONSTRAINT "student_time_block_student_id_student_id_fk" FOREIGN KEY ("student_id") REFERENCES "public"."student"("id") ON DELETE cascade ON UPDATE no action
);
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "idx_time_block_student" ON "student_time_block" USING btree ("student_id");
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "student_time_block_exception" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "student_time_block_exception_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"block_id" integer NOT NULL,
	"occurrence_date" date NOT NULL,
	"status" "time_block_exception_status" NOT NULL,
	"start_time" time,
	"end_time" time,
	CONSTRAINT "uq_time_block_exception" UNIQUE("block_id","occurrence_date"),
	CONSTRAINT "chk_time_block_exc_movido" CHECK (("student_time_block_exception"."status" = 'cancelled' AND "student_time_block_exception"."start_time" IS NULL AND "student_time_block_exception"."end_time" IS NULL) OR ("student_time_block_exception"."status" = 'moved' AND "student_time_block_exception"."start_time" IS NOT NULL AND "student_time_block_exception"."end_time" IS NOT NULL AND "student_time_block_exception"."end_time" > "student_time_block_exception"."start_time")),
	CONSTRAINT "chk_time_block_exc_grilla" CHECK ("student_time_block_exception"."start_time" IS NULL OR ("student_time_block_exception"."start_time" >= '07:00' AND "student_time_block_exception"."end_time" <= '22:00')),
	CONSTRAINT "student_time_block_exception_block_id_student_time_block_id_fk" FOREIGN KEY ("block_id") REFERENCES "public"."student_time_block"("id") ON DELETE cascade ON UPDATE no action
);
