-- RS-BE-55, RS-BE-57 y RS-BE-58 · Notas parciales de la ULima y horas de lectura
-- (specs/features/recarga-portal/recarga-portal.spec.md, «Modelo de datos»).
--
-- Crea una tabla y agrega dos columnas, y no toca ninguna fila.
--   student_portal_score                  una fila por evaluación que publica la ULima
--   enrollment.portal_grades_read_at      hora de la última lectura de notas
--   enrollment.portal_attendance_read_at  hora de la última lectura de asistencia
--
-- La tabla cuelga de enrollment con ON DELETE CASCADE, porque sus filas son una
-- copia de lo que publica la ULima y no tienen sentido sin su matrícula, y así
-- los dos scripts que borran matrículas (propuesta_855.ts y
-- delegados_secciones.ts) no fallan con 23503 (decisión abierta 5).
--
-- Aditiva e idempotente, con IF NOT EXISTS en cada sentencia, así que se puede
-- aplicar dos veces sin daño. Se aplica con
--
--   bun run db:apply drizzle/0015_portal_scores.sql
--
-- y no con db:migrate ni db:generate, porque drizzle/meta/_journal.json sigue en
-- la 0009. La aplica el dueño, con respaldo previo y su permiso explícito, antes
-- de desplegar el código que la usa, porque la importación escribe la columna
-- nueva y contra una base sin ella fallaría entera (RS-BE-58). Se registra en
-- MIGRATIONS.md con su fecha, su respaldo y su verificación. La 0014 es la de
-- student_specialty_test_result, en la rama feat/test-especialidad.

CREATE TABLE IF NOT EXISTS student_portal_score (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  enrollment_id integer NOT NULL REFERENCES enrollment(id) ON DELETE CASCADE,
  portal_key varchar(20) NOT NULL,
  group_name varchar(60),
  name varchar(150) NOT NULL,
  week_number smallint,
  weight numeric(5,2) NOT NULL,
  value numeric(4,2),
  mark varchar(10) NOT NULL,
  assessment_id integer REFERENCES assessment(id),
  match_rule varchar(20) NOT NULL,
  CONSTRAINT uq_student_portal_score_key UNIQUE (enrollment_id, portal_key),
  CONSTRAINT chk_student_portal_score_weight CHECK (weight > 0 AND weight <= 100),
  CONSTRAINT chk_student_portal_score_week CHECK (week_number IS NULL OR week_number BETWEEN 1 AND 20),
  CONSTRAINT chk_student_portal_score_value CHECK (value IS NULL OR value BETWEEN 0 AND 20),
  CONSTRAINT chk_student_portal_score_mark CHECK (mark IN ('graded', 'pending', 'np')),
  CONSTRAINT chk_student_portal_score_mark_value CHECK ((mark = 'graded') = (value IS NOT NULL)),
  CONSTRAINT chk_student_portal_score_match CHECK (match_rule IN ('exact', 'exact_other_name', 'week_shift', 'none')),
  CONSTRAINT chk_student_portal_score_match_assessment CHECK ((match_rule = 'none') = (assessment_id IS NULL))
);
CREATE UNIQUE INDEX IF NOT EXISTS uq_student_portal_score_assessment
  ON student_portal_score (enrollment_id, assessment_id) WHERE assessment_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_student_portal_score_enrollment
  ON student_portal_score (enrollment_id);

ALTER TABLE enrollment ADD COLUMN IF NOT EXISTS portal_grades_read_at timestamptz;
ALTER TABLE enrollment ADD COLUMN IF NOT EXISTS portal_attendance_read_at timestamptz;
