import { describe, expect, test } from "bun:test";
import { getTableConfig } from "drizzle-orm/pg-core";
import { enrollment, studentPortalScore } from "../../src/db/schema/schema.js";

/**
 * Modelo de datos de recarga-portal.spec.md (migración 0015).
 *
 * El .sql se lee como texto, así que esta prueba no aplica la migración ni toca
 * ninguna base. Aplicarla es del dueño, con respaldo y permiso (MIGRATIONS.md).
 * Los comentarios del encabezado se quitan antes de contar, para que una
 * palabra del texto no cuente como sentencia.
 */
const migracion = await Bun.file("drizzle/0015_portal_scores.sql").text();
const sentencias = migracion
  .split("\n")
  .filter((l) => !l.trimStart().startsWith("--"))
  .join("\n");
const veces = (aguja: string): number => sentencias.split(aguja).length - 1;

const CHECKS = [
  "chk_student_portal_score_mark",
  "chk_student_portal_score_mark_value",
  "chk_student_portal_score_match",
  "chk_student_portal_score_match_assessment",
  "chk_student_portal_score_value",
  "chk_student_portal_score_week",
  "chk_student_portal_score_weight",
];

describe("drizzle/0015_portal_scores.sql", () => {
  test("crea una sola tabla, con IF NOT EXISTS y su identidad", () => {
    expect(sentencias).toContain("CREATE TABLE IF NOT EXISTS student_portal_score (");
    expect(veces("CREATE TABLE")).toBe(1);
    expect(sentencias).toContain("id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY");
  });

  test("la matrícula borra en cascada y la evaluación del sílabo no", () => {
    expect(sentencias).toContain(
      "enrollment_id integer NOT NULL REFERENCES enrollment(id) ON DELETE CASCADE",
    );
    expect(sentencias).toContain("assessment_id integer REFERENCES assessment(id),");
    expect(veces("ON DELETE CASCADE")).toBe(1);
  });

  test("el UNIQUE y los siete CHECK llevan el nombre y la condición de la spec", () => {
    for (const restriccion of [
      "uq_student_portal_score_key UNIQUE (enrollment_id, portal_key)",
      "chk_student_portal_score_weight CHECK (weight > 0 AND weight <= 100)",
      "chk_student_portal_score_week CHECK (week_number IS NULL OR week_number BETWEEN 1 AND 20)",
      "chk_student_portal_score_value CHECK (value IS NULL OR value BETWEEN 0 AND 20)",
      "chk_student_portal_score_mark CHECK (mark IN ('graded', 'pending', 'np'))",
      "chk_student_portal_score_mark_value CHECK ((mark = 'graded') = (value IS NOT NULL))",
      "chk_student_portal_score_match CHECK (match_rule IN ('exact', 'exact_other_name', 'week_shift', 'none'))",
      "chk_student_portal_score_match_assessment CHECK ((match_rule = 'none') = (assessment_id IS NULL))",
    ]) {
      expect(sentencias).toContain(`CONSTRAINT ${restriccion}`);
    }
    expect(veces("CHECK (")).toBe(7);
  });

  test("los dos índices son idempotentes", () => {
    expect(sentencias).toContain(
      "CREATE UNIQUE INDEX IF NOT EXISTS uq_student_portal_score_assessment\n  ON student_portal_score (enrollment_id, assessment_id) WHERE assessment_id IS NOT NULL;",
    );
    expect(sentencias).toContain(
      "CREATE INDEX IF NOT EXISTS idx_student_portal_score_enrollment\n  ON student_portal_score (enrollment_id);",
    );
    expect(veces("INDEX IF NOT EXISTS")).toBe(2);
  });

  test("las dos horas de lectura son columnas nulables de enrollment", () => {
    expect(sentencias).toContain(
      "ALTER TABLE enrollment ADD COLUMN IF NOT EXISTS portal_grades_read_at timestamptz;",
    );
    expect(sentencias).toContain(
      "ALTER TABLE enrollment ADD COLUMN IF NOT EXISTS portal_attendance_read_at timestamptz;",
    );
    expect(veces("ALTER TABLE")).toBe(2);
  });

  test("es aditiva y no nombra db:push", () => {
    expect(sentencias).not.toContain("DROP");
    expect(sentencias).not.toContain("ADD VALUE");
    // Las dos columnas nuevas no llevan DEFAULT, así que no reescriben ninguna fila.
    const altas = sentencias.split("\n").filter((l) => l.startsWith("ALTER TABLE"));
    expect(altas.every((l) => !l.includes("DEFAULT"))).toBe(true);
    expect(migracion).not.toContain("db:push");
  });
});

describe("schema.ts sigue a la 0015", () => {
  const tabla = getTableConfig(studentPortalScore);

  test("mismas columnas, tipos y nulabilidad", () => {
    expect(tabla.name).toBe("student_portal_score");
    expect(Object.fromEntries(tabla.columns.map((c) => [c.name, c.getSQLType()]))).toEqual({
      id: "integer",
      enrollment_id: "integer",
      portal_key: "varchar(20)",
      group_name: "varchar(60)",
      name: "varchar(150)",
      week_number: "smallint",
      weight: "numeric(5, 2)",
      value: "numeric(4, 2)",
      mark: "varchar(10)",
      assessment_id: "integer",
      match_rule: "varchar(20)",
    });
    expect(tabla.columns.filter((c) => !c.notNull).map((c) => c.name).sort()).toEqual([
      "assessment_id", "group_name", "value", "week_number",
    ]);
  });

  test("la FK a enrollment borra en cascada y la de assessment no", () => {
    const fks = tabla.foreignKeys.map((fk) => ({
      columna: fk.reference().columns[0]!.name,
      destino: getTableConfig(fk.reference().foreignTable).name,
      alBorrar: fk.onDelete ?? "no action",
    }));
    expect(fks).toContainEqual({ columna: "enrollment_id", destino: "enrollment", alBorrar: "cascade" });
    const aAssessment = fks.find((f) => f.columna === "assessment_id");
    expect(aAssessment?.destino).toBe("assessment");
    expect(aAssessment?.alBorrar).not.toBe("cascade");
    expect(fks).toHaveLength(2);
  });

  test("los CHECK, el UNIQUE y los índices llevan el nombre de la migración", () => {
    expect(tabla.checks.map((c) => c.name).sort()).toEqual(CHECKS);
    expect(tabla.uniqueConstraints.map((u) => u.name)).toEqual(["uq_student_portal_score_key"]);
    expect(tabla.indexes.map((i) => i.config.name).sort()).toEqual([
      "idx_student_portal_score_enrollment",
      "uq_student_portal_score_assessment",
    ]);
  });

  test("enrollment suma las dos horas, nulables y con zona horaria", () => {
    const columnas = Object.fromEntries(getTableConfig(enrollment).columns.map((c) => [c.name, c]));
    for (const nombre of ["portal_grades_read_at", "portal_attendance_read_at"]) {
      expect(columnas[nombre]?.getSQLType()).toBe("timestamp with time zone");
      expect(columnas[nombre]?.notNull).toBe(false);
    }
  });
});
