import { describe, expect, test } from "bun:test";
import { getTableConfig, type PgTable } from "drizzle-orm/pg-core";
import {
  studentTimeBlock,
  studentTimeBlockException,
  timeBlockExceptionStatusEnum,
} from "../../src/db/schema/schema.js";

// El .sql se lee como texto plano: esta prueba NO aplica la migracion ni toca
// la base. Aplicarla es del dueno (MIGRATIONS.md).
const migracion = await Bun.file("drizzle/0012_time_blocks.sql").text();

const veces = (aguja: string): number => migracion.split(aguja).length - 1;

const columnas = (tabla: PgTable): string[] => getTableConfig(tabla).columns.map((c) => c.name);

const tipos = (tabla: PgTable): Record<string, string> =>
  Object.fromEntries(getTableConfig(tabla).columns.map((c) => [c.name, c.getSQLType()]));

const nulables = (tabla: PgTable): string[] =>
  getTableConfig(tabla).columns.filter((c) => !c.notNull).map((c) => c.name);

describe("drizzle/0012_time_blocks.sql", () => {
  test("crea las dos tablas y ninguna mas, las dos con IF NOT EXISTS y su identidad", () => {
    expect(migracion).toContain('CREATE TABLE IF NOT EXISTS "student_time_block"');
    expect(migracion).toContain('CREATE TABLE IF NOT EXISTS "student_time_block_exception"');
    expect(veces("CREATE TABLE")).toBe(2);
    expect(veces("PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY")).toBe(2);
  });

  test("el tipo nuevo se crea una sola vez y guardado contra duplicate_object", () => {
    expect(migracion).toContain(
      `DO $$ BEGIN\n  CREATE TYPE "public"."time_block_exception_status" AS ENUM('cancelled', 'moved');\nEXCEPTION WHEN duplicate_object THEN NULL;\nEND $$;`,
    );
    expect(veces("CREATE TYPE")).toBe(1);
    // Crear un tipo SI es transaccional; la trampa de MIGRATIONS.md:125 es
    // agregarle un valor a un tipo que ya existe, que revienta dentro de db:apply.
    expect(migracion).not.toContain("ADD VALUE");
  });

  test("el indice por alumno tambien es idempotente", () => {
    expect(migracion).toContain(
      'CREATE INDEX IF NOT EXISTS "idx_time_block_student" ON "student_time_block" USING btree ("student_id")',
    );
    expect(veces("CREATE INDEX")).toBe(1);
  });

  test("es aditiva: no altera ni borra nada de lo que ya existe, y no usa db:push", () => {
    expect(migracion).not.toContain("ALTER TABLE");
    expect(migracion).not.toContain("DROP");
    expect(migracion).not.toContain("db:push");
    expect(veces("--> statement-breakpoint")).toBe(3);
  });

  test("las dos claves foraneas son las unicas y borran en cascada", () => {
    expect(veces("FOREIGN KEY")).toBe(2);
    expect(veces("ON DELETE cascade")).toBe(2);
    expect(migracion).toContain(
      'CONSTRAINT "student_time_block_student_id_student_id_fk" FOREIGN KEY ("student_id") REFERENCES "public"."student"("id") ON DELETE cascade ON UPDATE no action',
    );
    expect(migracion).toContain(
      'CONSTRAINT "student_time_block_exception_block_id_student_time_block_id_fk" FOREIGN KEY ("block_id") REFERENCES "public"."student_time_block"("id") ON DELETE cascade ON UPDATE no action',
    );
  });

  test("no se ata a curso, seccion, ciclo ni matricula", () => {
    expect(migracion).not.toContain('REFERENCES "public"."section"');
    expect(migracion).not.toContain('REFERENCES "public"."course"');
    expect(migracion).not.toContain('REFERENCES "public"."course_offering"');
    expect(migracion).not.toContain('REFERENCES "public"."academic_period"');
    expect(migracion).not.toContain('REFERENCES "public"."enrollment"');
    expect(migracion).not.toContain('REFERENCES "public"."schedule_session"');
  });

  test("los seis CHECK de la regla, con el nombre que fija la spec", () => {
    expect(migracion).toContain(
      'CONSTRAINT "chk_time_block_horas" CHECK ("student_time_block"."end_time" > "student_time_block"."start_time")',
    );
    expect(migracion).toContain(
      `CONSTRAINT "chk_time_block_grilla" CHECK ("student_time_block"."start_time" >= '07:00' AND "student_time_block"."end_time" <= '22:00')`,
    );
    expect(migracion).toContain(
      'CONSTRAINT "chk_time_block_fechas" CHECK ("student_time_block"."end_date" >= "student_time_block"."start_date")',
    );
    // El coalesce no es adorno: sobre un arreglo vacio array_length devuelve
    // NULL, y una restriccion que evalua a NULL se da por satisfecha, asi que
    // sin el coalesce un days_of_week vacio entraria a la tabla.
    expect(migracion).toContain(
      'CONSTRAINT "chk_time_block_dias" CHECK (coalesce(array_length("student_time_block"."days_of_week", 1), 0) BETWEEN 1 AND 7 AND "student_time_block"."days_of_week" <@ ARRAY[1,2,3,4,5,6,7]::smallint[])',
    );
    expect(migracion).toContain(
      `CONSTRAINT "chk_time_block_color" CHECK ("student_time_block"."color_hex" ~ '^#[0-9A-Fa-f]{6}$')`,
    );
    expect(migracion).toContain(
      'CONSTRAINT "chk_time_block_titulo" CHECK (length(btrim("student_time_block"."title")) BETWEEN 1 AND 60)',
    );
  });

  test("los dos CHECK de la excepcion y su UNIQUE", () => {
    expect(migracion).toContain(
      'CONSTRAINT "chk_time_block_exc_movido" CHECK (("student_time_block_exception"."status" = \'cancelled\' AND "student_time_block_exception"."start_time" IS NULL AND "student_time_block_exception"."end_time" IS NULL) OR ("student_time_block_exception"."status" = \'moved\' AND "student_time_block_exception"."start_time" IS NOT NULL AND "student_time_block_exception"."end_time" IS NOT NULL AND "student_time_block_exception"."end_time" > "student_time_block_exception"."start_time"))',
    );
    expect(migracion).toContain(
      `CONSTRAINT "chk_time_block_exc_grilla" CHECK ("student_time_block_exception"."start_time" IS NULL OR ("student_time_block_exception"."start_time" >= '07:00' AND "student_time_block_exception"."end_time" <= '22:00'))`,
    );
    expect(migracion).toContain(
      'CONSTRAINT "uq_time_block_exception" UNIQUE("block_id","occurrence_date")',
    );
    expect(veces("CHECK (")).toBe(8);
  });

  test("los tipos de las columnas son los de la spec", () => {
    expect(migracion).toContain('"title" varchar(60) NOT NULL');
    expect(migracion).toContain('"color_hex" varchar(7) NOT NULL');
    expect(migracion).toContain('"days_of_week" smallint[] NOT NULL');
    expect(migracion).toContain('"start_time" time NOT NULL,');
    expect(migracion).toContain('"end_time" time NOT NULL,');
    expect(migracion).toContain('"start_date" date NOT NULL');
    expect(migracion).toContain('"end_date" date NOT NULL');
    expect(migracion).toContain('"created_at" timestamp with time zone DEFAULT now() NOT NULL');
    expect(migracion).toContain('"updated_at" timestamp with time zone DEFAULT now() NOT NULL');
    expect(migracion).toContain('"occurrence_date" date NOT NULL');
    expect(migracion).toContain('"status" "time_block_exception_status" NOT NULL');
    // Sin NOT NULL y con la coma: solo las horas de la excepcion son nulables.
    expect(migracion).toContain('"start_time" time,');
    expect(migracion).toContain('"end_time" time,');
  });

  test("la cabecera dice como se aplica", () => {
    expect(migracion.trimStart().startsWith("--")).toBe(true);
    expect(migracion).toContain("bun run db:apply drizzle/0012_time_blocks.sql");
  });
});

describe("schema.ts · student_time_block", () => {
  test("nombre de tabla y columnas, en orden", () => {
    expect(getTableConfig(studentTimeBlock).name).toBe("student_time_block");
    expect(columnas(studentTimeBlock)).toEqual([
      "id",
      "student_id",
      "title",
      "color_hex",
      "days_of_week",
      "start_time",
      "end_time",
      "start_date",
      "end_date",
      "created_at",
      "updated_at",
    ]);
  });

  test("tipos sql: los dias son un arreglo de smallint y las fechas son date", () => {
    expect(tipos(studentTimeBlock)).toEqual({
      id: "integer",
      student_id: "integer",
      title: "varchar(60)",
      color_hex: "varchar(7)",
      days_of_week: "smallint[]",
      start_time: "time",
      end_time: "time",
      start_date: "date",
      end_date: "date",
      created_at: "timestamp with time zone",
      updated_at: "timestamp with time zone",
    });
  });

  test("ninguna columna de la regla es nulable, y el id es la PK", () => {
    expect(nulables(studentTimeBlock)).toEqual([]);
    const id = getTableConfig(studentTimeBlock).columns.find((c) => c.name === "id");
    expect(id?.primary).toBe(true);
  });

  test("seis CHECK, un indice por alumno y ningun UNIQUE", () => {
    const cfg = getTableConfig(studentTimeBlock);
    expect(cfg.checks.map((k) => k.name)).toEqual([
      "chk_time_block_horas",
      "chk_time_block_grilla",
      "chk_time_block_fechas",
      "chk_time_block_dias",
      "chk_time_block_color",
      "chk_time_block_titulo",
    ]);
    expect(cfg.indexes.map((i) => i.config.name)).toEqual(["idx_time_block_student"]);
    expect(cfg.uniqueConstraints).toEqual([]);
  });

  test("una sola FK, a student, en cascada", () => {
    const fks = getTableConfig(studentTimeBlock).foreignKeys;
    expect(fks.length).toBe(1);
    expect(fks[0]?.getName()).toBe("student_time_block_student_id_student_id_fk");
    expect(fks[0]?.onDelete).toBe("cascade");
    expect(fks[0]?.reference().foreignColumns.map((c) => c.name)).toEqual(["id"]);
  });
});

describe("schema.ts · student_time_block_exception", () => {
  test("nombre de tabla y columnas, en orden", () => {
    expect(getTableConfig(studentTimeBlockException).name).toBe("student_time_block_exception");
    expect(columnas(studentTimeBlockException)).toEqual([
      "id",
      "block_id",
      "occurrence_date",
      "status",
      "start_time",
      "end_time",
    ]);
  });

  test("tipos sql, y solo las horas son nulables", () => {
    expect(tipos(studentTimeBlockException)).toEqual({
      id: "integer",
      block_id: "integer",
      occurrence_date: "date",
      status: "time_block_exception_status",
      start_time: "time",
      end_time: "time",
    });
    expect(nulables(studentTimeBlockException)).toEqual(["start_time", "end_time"]);
  });

  test("UNIQUE por bloque y fecha, dos CHECK y FK al bloque en cascada", () => {
    const cfg = getTableConfig(studentTimeBlockException);
    expect(cfg.uniqueConstraints.map((u) => u.name)).toEqual(["uq_time_block_exception"]);
    expect(cfg.uniqueConstraints[0]?.columns.map((c) => c.name)).toEqual([
      "block_id",
      "occurrence_date",
    ]);
    expect(cfg.checks.map((k) => k.name)).toEqual([
      "chk_time_block_exc_movido",
      "chk_time_block_exc_grilla",
    ]);
    expect(cfg.foreignKeys.length).toBe(1);
    expect(cfg.foreignKeys[0]?.getName()).toBe(
      "student_time_block_exception_block_id_student_time_block_id_fk",
    );
    expect(cfg.foreignKeys[0]?.onDelete).toBe("cascade");
  });
});

describe("schema.ts · time_block_exception_status", () => {
  test("el enum tiene los dos estados de la spec y ninguno mas", () => {
    expect(timeBlockExceptionStatusEnum.enumName).toBe("time_block_exception_status");
    expect(timeBlockExceptionStatusEnum.enumValues).toEqual(["cancelled", "moved"]);
  });
});
